### ISSUE TITLE
how to set "run whether user is logged on or not"

### ISSUE THREAD

**Issue by lluis** [djberg96/win32-taskscheduler#11]
Hi,
I defined this task:

```
ts = TaskScheduler.new
trigger = {
  trigger_type: TaskScheduler::AT_SYSTEMSTART,
  start_year: 2014,
  start_month: 1,
  start_day: 1,
  start_hour: 0,
  start_minute: 0,
  minutes_interval: 5,
}
ts.new_work_item('test', trigger)
ts.application_name = 'notepad.exe'
ts.activate('test')
```

but I need to set "run whether user is logged on or not" , how can I do this?
thanks!

**Comment by MaxLap** [comment]
I had to do this too. It has been a while, but if i remember correctly, you need to set the password attribute on your ts to the actual password of the user you want the task to run as.

    ts.password = my_password

So when setting it up, you might want to have a prompt asking for the password.

**Comment by djberg96** [comment]
There's a pretty big thread about it here:

https://social.technet.microsoft.com/Forums/windows/en-US/c03d6691-b058-4f8d-961c-e8eba25bbaed/task-scheduler-problem-run-whether-user-is-logged-on-or-not?forum=w7itprogeneral

A few people have suggested that providing a full path to the app name solved their problem. So, "C:\path\to\notepad.exe" instead of just "notepad.exe". I think @MaxLap's solution works as well.

**Comment by djberg96** [comment]
Actually, I would think that should be the default setting. There's the TASK_FLAG_RUN_ONLY_IF_LOGGED_ON flag to explicitly require credentials, at which point you must specify user/password info.

@phasis68 Any ideas?

**Comment by phasis68** [comment]
Calling set_account_information makes the task to "run whether user is logged on or not".

In the above code, 
Insert 
`ts.set_account_information(userid, password)`
before 
`ts.activate('test')`

**Comment by djberg96** [comment]
@phasis68 thanks!
